export module isolated_js;
export import :deferred_receiver;
export import :dictionary.vector_of;
export import :enum_.types;
export import :function;
export import :functional;
export import :intrinsics.error;
export import :intrinsics.external;
export import :property;
export import :reference_of;
export import :referential_value;
export import :struct_.types;
export import :transfer;
export import :tuple.accept; // for `rest`
export import :union_.types;
export import :value;
export import :variant.types;
import :builtin.accept;
import :builtin.visit;
import :dictionary.accept;
import :dictionary.visit;
import :enum_.accept;
import :reference.accept;
import :reference.visit;
import :struct_.accept;
import :struct_.visit;
import :tuple.visit;
import :union_.accept;
import :variant.accept;
import :variant.visit;
import :vector.accept;
import :vector.visit;
