export module isolated_js;
export import isolated_js.date;
export import isolated_js.dictionary.vector_of;
export import isolated_js.enum_.types;
export import isolated_js.function;
export import isolated_js.primitive.types;
export import isolated_js.property;
export import isolated_js.struct_.types;
export import isolated_js.tag;
export import isolated_js.transfer;
export import isolated_js.union_.types;
export import isolated_js.value;
import isolated_js.dictionary.accept;
import isolated_js.dictionary.visit;
import isolated_js.enum_.accept;
import isolated_js.primitive.accept;
import isolated_js.primitive.visit;
import isolated_js.struct_.accept;
import isolated_js.struct_.visit;
export import isolated_js.tuple.accept;
import isolated_js.tuple.visit;
import isolated_js.union_.accept;
import isolated_js.variant.accept;
import isolated_js.variant.visit;
import isolated_js.vector.accept;
import isolated_js.vector.visit;
