#!/bin/sh
# Use the c preprocessor to expand command-line macros. This works around the draconian P3034R1
# standard.
# Usage: expand_def source.cc -Dfrom=to
set -eu
FILE="$1"
shift

replace() {
	sed -E -e "s/(\s*#)/__REMOVE_PRE__\1/" -e "s/^\s*\/\/([A-Za-z0-9 ()_\-]+$)/__COMMENT__\1/" | \
	cpp -E "$@" | \
	sed -E -e "s/__REMOVE_PRE__//" -e "s/__COMMENT__/\/\//" | \
	grep -Ev "^# [01]"
}

# nb: First line *must* be the module declaration, if it exists. So the `#line` directive happens
# after that.
CONTENT=$(cat "$FILE")
echo "$CONTENT" | head -n1 | replace "$@"
echo "#line 2 \"$FILE\""
echo "$CONTENT" | tail -n+2 | replace "$@"
