#!/bin/sh
# Output `host-arch` identifier, hopefully matching logic in backend_v8.js
set -eu
case $(uname -m) in
	aarch64|arm64)
		ARCH=arm64 ;;
	x86_64|amd64)
		ARCH=x64 ;;
	*)
		exit 1
esac

case $(uname -o) in
	Darwin)
		PLATFORM=darwin ;;
	GNU/Linux)
		PLATFORM=linux-gnu ;;
	Linux)
		if [ -f /etc/alpine-release ]; then
			PLATFORM=linux-musl
		fi ;;
	Msys)
		PLATFORM=win32 ;;
	*)
		exit 1
esac

echo "${PLATFORM}-${ARCH}"
