FROM node:22-bookworm-slim AS build
WORKDIR /isolated-vm
RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  g++ \
  make \
  python3
COPY . .
RUN npm install --ignore-scripts
RUN npm run prebuild
FROM scratch
COPY --from=build /isolated-vm/prebuilds .
