FROM node:22-bookworm-slim AS build
WORKDIR /isolated-vm
RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  g++-11 \
  make \
  python3
COPY . .
RUN npm install --ignore-scripts
RUN CXX=g++-11 MAKEFLAGS=-j$(nproc) npx -y prebuild
FROM scratch
COPY --from=build /isolated-vm/prebuilds .
