publishBranch: experimental
packages:
  - packages/auto_js/example
  - packages/auto_js/js
  - packages/auto_js/napi
  - packages/auto_js/v8
  - packages/backend_napi_v8
  - packages/isolated-vm
  - packages/third_party/nodejs
  - packages/utility
