# Checkout v8 sources at the given version, and sync deps
FROM isolated-vm/v8_git AS git
ARG V8_VERSION
RUN git clone file:///v8 --branch $V8_VERSION --depth 1 --single-branch head

FROM isolated-vm/depot_tools AS sources
COPY --from=git head v8
RUN <<DONE
	set -eux
	gclient config --unmanaged https://chromium.googlesource.com/v8/v8.git
	gclient sync --no-history --shallow --with_branch_heads
DONE
FROM scratch
COPY --from=sources v8 .
