# Image w/ depot_tools & other prerequisites installed
FROM debian
RUN <<DONE
	set -eux
	apt-get update
	apt-get install -y \
		curl \
		git \
		python3 \
	;
	mkdir -p ~/.config/depot_tools
	echo '{"is-googler":false,"countdown":10,"opt-in":null,"version":3}' > ~/.config/depot_tools/metrics.cfg
	git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git --depth 1
	PATH=$PATH:/depot_tools update_depot_tools
DONE
ENV PATH=$PATH:/depot_tools
