export module auto_js;
export import :deferred_receiver;
export import :enum_.types;
export import :function;
export import :functional;
export import :intrinsics.array_buffer;
export import :intrinsics.error;
export import :intrinsics.external;
export import :property;
export import :reference_of;
export import :referential_value;
export import :struct_.types;
export import :transfer;
export import :tuple.accept; // for `rest`
export import :union_.types;
export import :value;
export import :variant.types;
export import :vector.vector_of;
#if __GNUC__
export import :builtin.accept;
export import :builtin.visit;
export import :enum_.accept;
export import :enum_.visit;
export import :reference.accept;
export import :reference.visit;
export import :struct_.accept;
export import :struct_.visit;
export import :tuple.visit;
export import :union_.accept;
export import :tag;
export import :variant.accept;
export import :variant.visit;
export import :vector.accept;
export import :vector.visit;
#else
import :builtin.accept;
import :builtin.visit;
import :enum_.accept;
import :enum_.visit;
import :reference.accept;
import :reference.visit;
import :struct_.accept;
import :struct_.visit;
import :tuple.visit;
import :union_.accept;
import :variant.accept;
import :variant.visit;
import :vector.accept;
import :vector.visit;
#endif
