description: Setup `gn` tool on this runner

inputs:
  triplet:
    required: true

runs:
  using: composite
  steps:
    # Just install depot_tools if not musl. The rest is skipped on non-container non-linux platforms
    # because `newkdev/setup-depot-tools` is invoked in the v8 action.
    - shell: sh
      if: endsWith(inputs.triplet, '-linux-gnu')
      run: |
        set -ux
        DEPOT_TOOLS=$RUNNER_TOOL_CACHE/depot_tools
        mkdir -p ~/.config/depot_tools
        echo '{"is-googler":false,"countdown":10,"opt-in":null,"version":3}' > ~/.config/depot_tools/metrics.cfg
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git --depth 1 "$DEPOT_TOOLS"
        PATH=$PATH:$DEPOT_TOOLS
        update_depot_tools
        echo "$DEPOT_TOOLS" >> "$GITHUB_PATH"

    # GNU `tar` & `zstd` is needed for `actions/cache`. Also, clang, for building.
    - uses: laverdet/install@v0.0.8
      if: endsWith(inputs.triplet, '-linux-musl')
      with:
        packages: clang tar zstd

    # Restore musl cache
    - uses: actions/cache/restore@v4
      id: cache
      if: endsWith(inputs.triplet, '-linux-musl')
      with:
        key: gn/${{ inputs.triplet }}
        path: ./deps/gn

    # Build musl gn on cache miss
    - shell: sh
      if: |
        steps.cache.outcome == 'success' &&
        steps.cache.outputs.cache-hit != 'true'
      run: |
        set -ux
        git clone https://gn.googlesource.com/gn deps/gn
        cd deps/gn
        CFLAGS=-D_LARGEFILE64_SOURCE build/gen.py
        ninja -C out

    # Save musl cache
    - uses: actions/cache/save@v4
      if: |
        steps.cache.outcome == 'success' &&
        steps.cache.outputs.cache-hit != 'true'
      with:
        key: ${{ steps.cache.outputs.cache-primary-key }}
        path: ./deps/gn

    # Add musl gn to PATH
    - shell: sh
      if: steps.cache.outcome == 'success'
      run: echo "$PWD/deps/gn/out" >> "$GITHUB_PATH"
