#!/bin/sh
if [ ! -f .env ]; then
	cat <<-EOF > .env
		CC=$(ls /lib/llvm-*/bin/clang)
		CXX=$(ls /lib/llvm-*/bin/clang++)
		NODE_DIST_DIR=/opt
		V8_BUNDLE_PATH=$(dirname "$(find /v8/out -name env | head -n1)")
EOF
fi
