#!/bin/sh
set -eu
VERSION=$(basename "$1")
mkdir -p "$1"
curl "https://nodejs.org/download/release/v$VERSION/node-v$VERSION-headers.tar.gz" | \
	tar xz --strip-components=3 --directory="$1"
echo "$1"
