description: Build v8

inputs:
  configuration:
    type: choice
    default: release
    options:
      - debug
      - optdebug
      - release
  container:
    type: string
  ref:
    required: true
    type: string
  triplet:
    required: true
    type: string

runs:
  using: composite
  steps:
    # Install dependencies
    - if: inputs.container == 'alpine:edge'
      name: Toolchain [Alpine]
      uses: laverdet/install@v1
      with:
        packages: |
          coreutils
          git
          linux-headers
          openssh
          patch
          pkgconf
          python3
          xz

    - if: inputs.container == 'debian:sid'
      name: Toolchain [Debian]
      uses: laverdet/install@v1
      with:
        packages: |
          ca-certificates
          coreutils
          git
          libglib2.0-dev
          pkgconf
          python3
          ssh
          xz-utils

    - if: runner.os == 'macOS'
      name: Toolchain [macOS]
      shell: sh
      run: brew install llvm

    # Install `gn`
    - uses: ./.github/actions/v8/gn
      with:
        triplet: ${{ inputs.triplet }}

    # Checkout and sync v8
    - uses: actions/checkout@v5
      with:
        path: ./deps/v8
        ref: ${{ inputs.ref }}
        repository: v8/v8
    - uses: ./.github/actions/v8/gclient-sync
    - shell: sh
      working-directory: deps/v8
      env:
        REF: ${{ inputs.ref }}
      run: |
        set -ux
        SKIP_SYNC=thanks PATCH_DIR="$GITHUB_WORKSPACE/patches" v8_select "$REF"

    # Linux builds require sysroot for libc version compatibility
    - shell: sh
      if: endsWith(inputs.triplet, '-linux-gnu')
      env:
        TRIPLET: ${{ inputs.triplet }}
      run: |
        set -ux
        echo ::group::Linux sysroot
        ARCH=$(triplet_util -t "$TRIPLET" %b)
        deps/v8/build/linux/sysroot_scripts/install-sysroot.py --arch "$ARCH"
        echo ::endgroup::

    # Finally, perform the v8 build
    - shell: sh
      working-directory: deps/v8
      env:
        REF: ${{ inputs.ref }}
        TARGET: ${{ inputs.triplet }}.${{ inputs.configuration }}
        TRIPLET: ${{ inputs.triplet }}
      run: |
        set -ux
        echo ::group::Configure v8
        case $(triplet_util -t "$TRIPLET" %o) in
          darwin)
            if ! "$CXX" --version | grep -q clang; then
              echo "Error: 'CXX' must be clang on macOS" 1>&2
              exit 1
            fi
            CLANG_BASE_PATH=$(realpath $(realpath "$CXX")/../..)
            ;;
        esac
        CLANG_BASE_PATH="${CLANG_BASE_PATH-}" DEPOT_TOOLS_WIN_TOOLCHAIN=0 v8_configure "out/$REF/$TARGET"
        . "out/$REF/$TARGET/env"
        echo ::endgroup::

        echo ::group::Build v8
        ninja -C "out/$REF/$TARGET" $V8_TARGETS
        rm -rf "out/$REF/$TARGET/gen"
        find out -type f ! -name env ! -name args.gn ! -name '*.a' ! -name '*.h' ! -name '*.lib' -delete -print
        find out -type d -empty -delete
        echo ::endgroup::
