description: Build v8

inputs:
  triplet:
    required: true
  # "debug", "optdebug", "release"
  configuration:
    default: release
  ref:
    required: true

runs:
  using: composite
  steps:
    # Install dependencies
    - uses: laverdet/install@v0.0.8
      if: runner.os == 'Linux'
      with:
        packages: |
          bash
          build-essential
          coreutils
          curl
          git
          ninja-build
          patch
          pkgconf
          python3
          ssh
          xz-utils
          alpine#linux-headers
          debian#ca-certificates
          debian#libglib2.0-dev
    - shell: sh
      if: runner.os == 'macOS'
      run: brew install llvm

    # Install `gn`
    - uses: ./.github/actions/v8/gn
      with:
        triplet: ${{ inputs.triplet }}

    # Checkout and sync v8
    - uses: actions/checkout@v4
      with:
        path: ./deps/v8
        ref: ${{ inputs.ref }}
        repository: v8/v8
    - uses: ./.github/actions/v8/gclient-sync
    - shell: sh
      working-directory: deps/v8
      env:
        REF: ${{ inputs.ref }}
      run: |
        set -ux
        SKIP_SYNC=thanks PATCH_DIR="$GITHUB_WORKSPACE/patches" v8_select "$REF"

    # Linux builds require sysroot for libc version compatibility
    - shell: sh
      if: endsWith(inputs.triplet, '-linux-gnu')
      env:
        TRIPLET: ${{ inputs.triplet }}
      run: |
        set -ux
        echo ::group::Linux sysroot
        ARCH=$(triplet_util -t "$TRIPLET" %b)
        deps/v8/build/linux/sysroot_scripts/install-sysroot.py --arch "$ARCH"
        echo ::endgroup::

    # Finally, perform the v8 build
    - shell: sh
      working-directory: deps/v8
      env:
        REF: ${{ inputs.ref }}
        TARGET: ${{ inputs.triplet }}.${{ inputs.configuration }}
        TRIPLET: ${{ inputs.triplet }}
      run: |
        set -ux
        echo ::group::Build v8
        case $(triplet_util -t "$TRIPLET" %o) in
          darwin)
            export CLANG_BASE_PATH="$(brew --cellar llvm)/$(brew list --versions llvm | cut -d' ' -f2 | sort -V | head -n1)"
            ;;
          windows)
            export DEPOT_TOOLS_WIN_TOOLCHAIN=0
            ;;
        esac
        v8_build "out/$REF/$TARGET"
        rm -rf "out/$REF/$TARGET/gen"
        find out -type f ! -name '*.a' ! -name '*.h' ! -name '*.lib' -delete
        find out -type d -empty -delete
        echo ::endgroup::
